/* DROP */

BEGIN EXECUTE IMMEDIATE 'DROP TABLE "cache"'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;--

/* STATEMENTS */

CREATE TABLE "cache" (
    "id" VARCHAR2(128) NOT NULL,
    "data" BLOB,
    "expire" INTEGER,
    CONSTRAINT "cache_PK" PRIMARY KEY ("id") ENABLE
);
